### ISSUE TITLE
Use same dataset as in other lessons

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/OpenRefine-ecology-lesson#10]
@naupaka created modified versions of the surveys.csv, plots.csv, and species.csv that can be cleaned up with OpenRefine. I think it would make sense to use these files instead of the file the lessons currently uses as they are simple modifications from what the other lessons use.

The files are here: https://github.com/datacarpentry/2015-05-14-wsu/tree/gh-pages/Workshop_Files/data/raw/tofix

**Comment by naupaka** [comment]
I modified the main dataset (the separate, un-joined portal csv files) to have errors that facilitate using the various features of OpenRefine. I have a list of the changes I made and how to fix them, and could add this to the instructor materials once I have a minute...

**Comment by debpaul** [comment]
Hi @naupaka will you have a chance to add the list of changes and how to fix them to the instructor materials anytime soon?

**Comment by debpaul** [comment]
@naupaka @fmichonneau another challenge then, is to figure out how to incoporate other folk's contributions that make changes to improve use of current dataset (example - to clustering section). If I merge their changes in, they won't apply to this new dataset.

**Comment by tracykteal** [comment]
Thanks all. I agree it would be great to use that dataset here.

**Comment by naupaka** [comment]
Sorry for the delay. Just got back from conference travel. Will open a PR with the changes this week.

**Comment by naupaka** [comment]
@debpaul also should note that I did hit on all the major features of OpenRefine in the modified datasets, including clustering, but not in all three csv files. So you might have looked at one that wasn't modified for that specific purpose.

**Comment by naupaka** [comment]
So I have added the things that have been modified in a list below. Additionally, all of the specific changes needed to get the 'broken' files above to be correct are available [here](https://github.com/datacarpentry/2015-05-14-wsu/tree/gh-pages/Workshop_Files/data/cleaned) in OpenRefine JSON format. 

My approach when teaching this material is to go through each of the columns in each of the three files, looking for outliers or inconsistencies with the tools appropriate to that type (e.g. outlier plots vs character-based clustering).

I am not sure where to put all of this information at the moment. It seems to me that building the lessons around fixing these files, instead of just generically demoing the features of OpenRefine, would be ideal, but it would also require a pretty substantial rewrite of the OpenRefine materials. In my mind, this fits nicely into a sequence from Excel -> OpenRefine -> SQL, but would also be omitted if needed without disrupting the continuity of the workshop narrative.

Alternatively, a link to the 'broken' data and a list of things to fix could go in the instructor notes and it could be left at that. 

Things to fix in example portal data csv files:

In `surveys.csv`:
* FF instead of F
* MM instead of M
* m instead of M
* f instead of F
* Errors in year column (extra 1s, extra 0s - I tried to make it unambiguous as to how they should be fixed)
* 9999 in weight column

In `species.csv`:
* 3 genus groups are off/incorrect
    * Select nearest-neighbor for clustering, and increase radius and lower number of block characters to find all problems
* "sp" vs "sp." vs "sp. " vs "sp.  "

In `plots.csv`:
* plot type naming consistency issues

**Comment by tracykteal** [comment]
For this release, we'll use the data that we have. But it would be good to update this lesson to use the same data as in the other lessons in the way suggested here.

**Comment by villanueval** [comment]
Closing old discussion.
