### ISSUE TITLE
better introduction to interface - submitted by email for instructor training checkout

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#152]
Better introduction to the interface of OpenRefine (for inclusion here http://www.datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/):

"The interface:
Once you have created, opened, or imported a project, the screen will update to display the rows or records of your data on the right. On the left, you will see tabs for Facet/Filter and Undo/Redo. 

For your data, as mentioned, it can be viewed as rows- similar to a spreadsheet- or records, which are rows that can be merged to create a single record of multi-rowed data. It can show as few as 5 rows/records at a time to at most 50 rows/records at a time. If your data is more than 50 rows/records, you can page through your data with the <<first, <previous, next>, and last>> links in the upper right of the gray toolbar. 

Important: Even though you cannot see all of your data in one window, it does not mean that transformations are not happening to that column of data when you perform that action. An action that is performed will execute on the entire column or selected data. More on this later on in the lesson.

In the upper right hand of the screen, you will also notice dropdowns for Extensions, Export, and a button for Open. These will be covered later in the lesson. 

Looking to the left of the screen, there is the pane for the Facet/Filter and Undo/Redo tabs. The Facet/Filter tab is where results for the faceting, filtering, clustering and more functions will appear when you perform those actions. Once you perform some actions, the Undo/Redo tab will list the actions you have completed with links that will allow you to move backward and forward through your actions as needed if you make a mistake and need to undo or redo. Extract and Apply in this tab will be covered later in the lesson.

For the columns:
Returning to your data rows/records in the right window, as mentioned, it will remind you of a spreadsheet format. If you designated your first row as column headers, these will appear in row 1. Next to those headers, you will see a drop down arrow with a dropdown menu. 

Important: Almost all of the transformation functions you will be performing will start with selecting the dropdown menu from the column headers to perform a function/action/transformation on the data in that column.

If you want to rename a column, click the dropdown arrow, scroll down to Edit column, and select Rename this column.

For the cells:
Clicking on a cell, you will notice the edit button appear in the upper right corner of each cell. If you click on the edit button, this will allow you to edit the data in that cell. Edit the data in the box and select Apply, Cancel, or Apply to All Identical Cells to perform that edit on more than one cell in that column. (This can also be done with Faceting and Clustering that is covered later in the lesson). 

Important: OpenRefine will automatically determine the data type of the value(s) in the cell you are editing. Once you edit a cell, it will default the data type to text (or string) values. If you are editing number, Boolean, or date data, select the corresponding data type from that drop down in the edit box before selecting Apply or Apply to All Identical Cells.

Remember, OpenRefine is better suited for structured or semi-structured data that require mass transformations and remediation. It is not useful for data entry." 

This should include screenshots.

And collapsing columns (related; also here http://www.datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/):

"If the interface is showing unnecessary columns that do not need data remediation or transformation, you can collapse them to create fewer columns that are visible in your window. Select a column that you do not need, click the down arrow, select View and Collapse this column. You can also collapse all columns but the column that is selected with Collapse all other columns. Columns to the left or right of the selected column can also be collapsed with Collapse all columns to left and Collapse all columns to right. If you want to un-collapse columns, go to the All column, click the down arrow, and select View and Expand all columns."

**Comment by kimdurante** [comment]
Reading through these suggestions, I would agree that a little more could be done to explain the interface. Perhaps though, I would not focus too much attention on features commonly available in spreadsheet applications (sorting, hiding/unhiding columns, etc.). 
However, I think more information on the following features might help:

- The difference between text and numeric facets. Perhaps even how to use timeline facets for certain data fields.

- How to reconcile terms from a taxonomy, such as GBIF, using a service. And how to add columns from the reconciled data. A pretty straightforward way to perform such a reconciliation is described [here:](http://iphylo.blogspot.com/2012/02/using-google-refine-and-taxonomic.html)

**Comment by Repositorian** [comment]
+1 to Kim's suggestions on explaining and demonstrating each facet and what it does.  At Caltech we've done so with the Portal Rodent dataset, including scatterplot to show location. 

Also we have added a regular expression segment to the lesson by looking for all sites in a particular location (e.g., a National Forest). And we've used reconcilation against Wikidata to add a new column for common names and GBIF to validate the scientific names.  

I think the regular expression and reconciliation exercises stand as discrete learning objectives that an Instructor can decide to cover or not, depending on time and the interests of the participants.

**Comment by Kakaalikins** [comment]
I also think that the introduction to the interface could be improved, specifically with respect to **step 4 during the "Creating a project" section of the "Working with OpenRefine"** lesson found here: [http://www.datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/](http://www.datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/)

Every time I've been a helper at an OpenRefine lesson, there are many questions from the audience during the preview section when importing a spreadsheet. As a result, I think that the steps for creating a project could be expanded to include a brief overview of the "_configure parsing options_" available to the user on import.

Perhaps the following settings could be noted during step 4:
 - before clicking "create project" you must select the correct character encoding. UTF-8 is the most widely used encoding and we'll select it here in order to ensure that all symbols in the dataset are parsed correctly
 - also ensure that you parse the first line as a column header
 - and have a look at how your dataset changes if you tick and un-tick the remaining options below

**Comment by debpaul** [comment]
These additions look good to me. Thanks for suggesting.

Sent from my iPhone

On Dec 18, 2017, at 5:44 AM, Kayleigh Roos <notifications@github.com<mailto:notifications@github.com>> wrote:


I also think that the introduction to the interface could be improved, specifically with respect to step 4 during the "Creating a project" section of the "Working with OpenRefine" lesson found here: http://www.datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.datacarpentry.org_OpenRefine-2Decology-2Dlesson_01-2Dworking-2Dwith-2Dopenrefine_&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=wJ-AAblyMHURVeLBz_4yUIDu6iZEhHZ7N6GQtDhs19s&s=vTk9_dDgiH5jS_jfI1hANY5p4BYX68Jj0z1EDpRPmow&e=>

Every time I've been a helper at an OpenRefine lesson, there are many questions from the audience during the preview section when importing a spreadsheet. As a result, I think that the steps for creating a project could be expanded to include a brief overview of the "configure parsing options" available to the user on import.

Perhaps the following settings could be noted during step 4:

  *   before clicking "create project" you must select the correct character encoding. UTF-8 is the most widely used encoding and we'll select it here in order to ensure that all symbols in the dataset are parsed correctly
  *   also ensure that you parse the first line as a column header
  *   and have a look at how your dataset changes if you tick and un-tick the remaining options below
