### ISSUE TITLE
suggestions - submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#204]
In relation to Open refine lesson, i have a suggestion: the second last part is teaching about scripts
I suggest just after that lesson , coding is introduced...that will build up on R lesson, i worked with some of the data (Species_id ) to code.
Moreover i was fascinated to realize that even if i cannot open zip folder on Open refine, it is possible to import more than two sheets in one window if you want to compare variables, provided the name of the column of those two sheets were the same.

**Comment by rachellombardi** [comment]
@pdoehle Introducing coding following the scripts lesson would certainly help lead into the coding lessons and could be a great idea to include. However, I wonder if it would lead to a whole slew of questions that instructors will touch on or build to in their subsequent R/python lessons. Personally, when I taught this workshop, I verbally touched on how scripting was related to coding, but I didn't want to go in too deep for fear of confusing learners before we learned the basics of coding later on. Do you think we should incorporate an introduction into coding or leave the lesson as is? 

The second idea of opening more than one Excel sheet at once is very interesting and something I looked in to. In order to show the leaners this feature, it would require us to edit the main spreadsheet they use for the lesson. Instead of undertaking this large change, I propose we add a note to the Instructor Notes about this feature so that they can describe it to leaners or explore it further if their class wants to learn more. Does this sound okay to you?

**Comment by villanueval** [comment]
Closing as submission sounds outside the scope of the lesson.
