### ISSUE TITLE
submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#216]
I would like to propose that a training dedicated OpenRefine be developed and linked to the lesson app so that when carrying out exercises, in order for one to have access to solution, the learner candidate be prompted by the system to try on their own first. This would prevent learner candidate from cheating by accessing lesson solutions without attempting to do the lesson on their own.

**Comment by rachellombardi** [comment]
@pdoehle This is an interesting idea, but might be challenging to incorporate and would also make this lesson have a different "feel" from the other Carpentry's materials. Since we do not know who submitted this issue originally, we cannot discuss it further with them. Therefore, are you okay with me closing this issue?

**Comment by ljvillanueva** [comment]
Closing issue since:

* there was no further comment 
* proposed idea seems far outside the scope of how Carpentries lessons work
* there is no grading, so no risk of cheating
* unclear how to even implement something like this
