### ISSUE TITLE
OpenRefine 3.4 strips whitespace by default

### ISSUE THREAD

**Issue by MikeTrizna** [datacarpentry/OpenRefine-ecology-lesson#245]
I know that the setup instructions [here](https://datacarpentry.org/ecology-workshop/setup-r-workshop.html#openrefine) specify using version 3.2, but I got excited that version 3.4 beta bundles Java in both the Windows and Mac installers. Dealing with Java has been our most common headache, so we decided to give the new version a shot for our most recent workshop.

Everything was going well, until we got to the [splitting section](https://datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/index.html#split) in Lesson 1. Only the learners with old versions were getting blank columns. It turns out that version 3.4 added a (super-useful) default feature to CSV import: "Trim leading & trailing whitespace from strings". See the screenshot below:

![image](https://user-images.githubusercontent.com/472677/82451033-74d51d00-9a7b-11ea-905f-85436a654335.png)

Nothing to change in the lesson material now since the lesson is written for 3.2, but something to keep an eye on...

Otherwise, the rest of the lesson seemed to work on 3.4, but we didn't cover all of the episodes.

**Comment by troub1** [comment]
I came here to report this same thing. For now, my planned "solution" is to just have them uncheck that box on import. So I don't know if it would be good to simply add that stipulation to the lesson? I can also see how it's easy enough to strip spaces later if you have to, and stripping things out on import (and changing the underlying data) before you've even looked at it makes me a little uneasy, so it seems like it's technically not even best practice to enable an option like that. But then again, it's leading/trailing whitespace, so _very_ unlikely to be actual data...

Either way, I think something needs to be added to the lesson script about it. I also think the setup instructions are unclear regarding the specific version, because there's the instructions that you link to but also these instructions in the lesson: https://datacarpentry.org/OpenRefine-ecology-lesson/setup.html that say "Download the software....Select the most recent version of OpenRefine." So that's how we ended up with 3.4. I also had someone for whom the regular version wouldn't work, so they had to download the bundled Java one, and that was a handy quick fix!

**Comment by ljvillanueva** [comment]
Version 3.4 added this option, turned on by default (OpenRefine/OpenRefine#791, [release notes for OpenRefine 3.4](https://github.com/OpenRefine/OpenRefine/wiki/Changes-for-3.4)).

There are a couple of options that have been suggested. Please vote by clicking on the option you prefer or enter your feedback as a comment:

[![](https://api.gh-polls.com/poll/01F6SW1P0915VNM9XYT508WJ1Z/Remove%20trim%20from%20lesson)](https://api.gh-polls.com/poll/01F6SW1P0915VNM9XYT508WJ1Z/Remove%20trim%20from%20lesson/vote)
[![](https://api.gh-polls.com/poll/01F6SW1P0915VNM9XYT508WJ1Z/Add%20instructions%20to%20uncheck%20the%20trim%20box)](https://api.gh-polls.com/poll/01F6SW1P0915VNM9XYT508WJ1Z/Add%20instructions%20to%20uncheck%20the%20trim%20box/vote)

**Comment by ljvillanueva** [comment]
Section removed and trim behavior noted in section on opening the file.

**Comment by MikeTrizna** [comment]
🙌
