### ISSUE TITLE
New Maintainers - Getting Started

### ISSUE THREAD

**Issue by pdoehle** [datacarpentry/OpenRefine-ecology-lesson#248]
Hi @rachellombardi,

I've read through all the issues and pull requests to get a general sense of what people are talking about on the lesson. Right now I have some general observations and would love to get your input:

- There are a large number of "quick fix" issues and pull requests in the form of typo and grammar fixes. A first step might be to have both of us sign off and close them out.
- Many open issues have been there for quite some time. How should we close these out? Should we try to revive the conversation on these threads?
- Are the [labels](https://github.com/datacarpentry/OpenRefine-ecology-lesson/labels) standardized? What are the conventions for employing them?
  - The [After-Lesson-Release](https://github.com/datacarpentry/OpenRefine-ecology-lesson/labels/after-lesson-release) label is on my issues. Is this for an upcoming release? Since some issues go back to 2015, is it still relevant?
- Several issue mention adding screen shots. We may need to check that these are still up to date as some of the issues have been there a while.
- It may be useful to come up with a set of [triage proceedures](https://steveklabnik.com/writing/how-to-be-an-open-source-gardener) or a check list.
  - How long do we wait for a response to close an issue?
  - We need to keep an eye out for issues that relate to each other.
  - How do we make effective use of labels?
- Some issues may need a wider discussion with the Curriculum Advisory Committee. @ErinBecker @angela-li Is there a Curriculum Advisory Committee for OpenRefine? Who should I reach out to?
  - Some issues ask about the length of the lesson since it is shorter than most lessons. Should it be longer? When we teach it at my institution, we teach it together with the Excel lesson material.
  - Many issues ask about including Google Refine Expression Language (GREL) in the lesson. I know it is mentioned briefly. Would this expand the lesson too much?

**Comment by rachellombardi** [comment]
Hi @pdoehle, 

Thank you so much for helping get the ball rolling! I have also read through many of the issues and pull requests. I have compiled responses to your questions, so please let me know your thoughts. 

**There are a large number of "quick fix" issues and pull requests in the form of typo and grammar fixes. A first step might be to have both of us sign off and close them out.**
I agree, I think that we should start with the "quick fix" issues. Once we address those, we might want to have our next step be a discussion with the entire Ecology curriculum maintainers about how much we want this lesson to change. Many of the issues/pull requests would require large rewrites to the lesson, so we could present a selection of the requested changes to the other maintainers and get an idea of whether they think it would be better to just make as many changes to the lesson as possible without rewriting the current underlying structure to the curriculum or if now is the time to rewrite/restructure the entire lesson. It seems this discussion has previously popped up before @datacarpentry/OpenRefine-ecology-lesson/issues/10 . Does this sound okay?

**Many open issues have been there for quite some time. How should we close these out? Should we try to revive the conversation on these threads?**
I believe we should do this on a case-by-case basis, depending on how crucial it is to have a discussion (especially for the older issues/requests). While it would be great it if we could revive all threads, I'm hesitant to do that because so many of them are _years_ old, we may not receive replies or many individuals may not remember the lesson well. I want to try to avoid us waiting to make a decision on an issue/pull because we are waiting for a response. What are your thoughts on this?

**Are the labels standardized? What are the conventions for employing them?
The After-Lesson-Release label is on my issues. Is this for an upcoming release? Since some issues go back to 2015, is it still relevant?**
As far as I am aware, there is no standardization or conventions for employing labels. I am also unsure of what dictates that an issue should receive an After-Lesson-Release label. Most of the items that are tagged with After-Lesson-Release have to deal with adding content, so they might refer to things that should be included in the next release. Regarding old issues from 2015ish, I would consider them still relevant unless the curriculum has changed such that the issue/request no longer applies or is irrelevant to today's versions of programs, etc.

**Several issue mention adding screen shots. We may need to check that these are still up to date as some of the issues have been there a while.**
I agree. 

**It may be useful to come up with a set of triage procedures or a check list.**
A suggested checklist: 
(1) Quick fixes (e.g. spelling mistakes)
(2) Fixes that would still apply even if the lesson was restructured (e.g. clarifying sections/ improving descriptions of things like faceting)
(3) Identify trends in "complex" or large issues that may require significant changes to the lesson 
(4) Present these trends to the Ecology maintainer team to obtain feedback about whether now is the time for potential major restructuring/rewriting of the material. Next steps will be assessed after this meeting. Once our next steps are solidified, this will influence how to update/add screenshots, etc.
Please let me know if you think we need a more detailed breakdown for our checklist. 

**How long do we wait for a response to close an issue?**
Perhaps two weeks to one month? Do you think that is too long/short? 

**We need to keep an eye out for issues that relate to each other.**
I agree! I'm hoping that by incorporating a step in our suggested checklist (step 3), we will be able to consolidate issues that relate to one another or contradict each other. 

**How do we make effective use of labels?**
Perhaps we can come up with a list of when to use certain labels.

**Comment by pdoehle** [comment]
@rachellombardi, that all sounds good to me. Let's start with step (1) of the checklist.

**Comment by pdoehle** [comment]
@rachellombardi, I went through and found the pull requests that involve quick punctuation fixes. Are you comfortable if I merge them?

**Comment by rachellombardi** [comment]
Hi @pdoehle, 

Thank you so much for keeping me in the loop! I saw that you merged many of these requests -thank you for doing so! Now that I am finished moving, I will be sure to keep a closer eye on these mentions.

**Comment by villanueval** [comment]
Archiving old discussion. Might be good to review after new team discusses priorities.
