### ISSUE TITLE
Create a "Date" column

### ISSUE THREAD

**Issue by tpoisot** [datacarpentry/OpenRefine-ecology-lesson#43]
So, some notes I gathered when using this lesson to prepare a class.

The transform `[cells["yr"].value, cells["mo"], cells["dy"].value].join("-")` will create the date as a yyyy-mm-dd value, which can be transform to a date in order to facet by time.

Is it worth mentioning?

**Comment by debpaul** [comment]
Yes +1

Sent from shoe (iPhone)

On Jan 18, 2017, at 3:06 PM, Timoth?e Poisot <notifications@github.com<mailto:notifications@github.com>> wrote:


So, some notes I gathered when using this lesson to prepare a class.

The transform [cells["yr"].value, cells["mo"], cells["dy"].value].join("-") will create the date as a yyyy-mm-dd value, which can be transform to a date in order to facet by time.

Is it worth mentioning?

-
